import './globals.css'
import { Inter } from 'next/font/google'

//fa
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

//context
import Context from './context';


import Navbar from './components/navbar'
import Footer from './components/footer'

const inter = Inter({ subsets: ['latin'], weight: '400', })

export const metadata = {
  title: 'My Forms',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className={inter.className}>
        <Context>
          <Navbar />
          {children}
          <Footer />
        </Context>
      </body>
    </html>
  )
}
